### ISSUE TITLE
Border radius on progress view

### ISSUE THREAD

**Issue by hsavit1** [codedailyio/react-native-animated-bar#1]
I'd like to create a borderRadius for the progress contents, not just the border around the progress bar. Is this possible with the current API?

**Comment by hsavit1** [comment]
To be clear, I'd like to have a borderWidth of 0, but I would still like to see the "liquid" contents of the progress bar with a border radius

**Comment by browniefed** [comment]
Ah yeah, good point. I can add in the ability to add styles to all of the items. There are more elegant ways to do this by pushing rendering over to the user I'm thinking of adding a

`fillStyle={}` and a `barStyle={}` which you can pass in whatever

**Comment by browniefed** [comment]
Went ahead and added 3 new stylings, described them in the README.

Install version `.20`

**Comment by browniefed** [comment]
Going to close this out, let me know if you feel like it's unresolved and we can reopenit

**Comment by hsavit1** [comment]
@browniefed awesome! thanks for responding back to this issue so quickly

I'm a little confused about how to use the new style rules. When I use the fillStyle prop with passing a borderRadius, I only am able to round the right side of the view. 

<img width="360" alt="screen shot 2017-08-15 at 4 13 18 pm" src="https://user-images.githubusercontent.com/5156236/29334232-baff8a80-81d4-11e7-9286-039e52ec6eb7.png">

**Comment by hsavit1** [comment]
Ahh. I see the problem. I need to apply the barStyle borderRadius as well

One thing that you might want to consider adding is the ability to square off the right side of the bar, while keeping the left side with a borderRadius

So in the above example, I'd like to round the left side of the blue bar and straighten its right side

**Comment by hsavit1** [comment]
Ahh. My fault! I just discovered that react native has support for the style props 'borderTopLeftRadius' and 'borderBottomLeftRadius'

This solved my issue. Thanks again for the help!

**Comment by browniefed** [comment]
Sorry was out and about.
The goal was to provide the simplest defaults as props. This just adds the ability to override styling for each view at any level. So ultimate customizability.

Also yes React Native allows you to round all and any corner you desire. `borderRadius` will do them all, then you can use those others to control specific corners.
