### ISSUE TITLE
How to stop the percentage?

### ISSUE THREAD

**Issue by valeriaabo** [codedailyio/react-native-animated-bar#2]
Hi! I dont get how can I put a static percentage, 
For example if I want the progress bar to stop at 50%., 
Or is there a congif option that I could just say "load until this value"

**Comment by browniefed** [comment]
Just set it to `progress={.5}` if you want it to be static at `50%`. You are in control of how the component works entirely. So if you are feeding it the value then just do a check on your end and never go above `.5`
